apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: journeyman/ecom-web:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: web-env-vars
        - secretRef:
            name: mysql-secret             
