apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ecom
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort
status:
  loadBalancer: {}
