apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycert
  namespace: ecom
spec:
  secretName: mycert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 82424f2d-c61e-4956-ab59-9d30f88ba52a.k8s.civo.com
  dnsNames:
  - 82424f2d-c61e-4956-ab59-9d30f88ba52a.k8s.civo.com

