apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycert
  namespace: ecom
spec:
  secretName: mycert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 0c8182d3-c0af-48e1-9db5-c3462e4d7d73.lb.civo.com
  dnsNames:
  - 0c8182d3-c0af-48e1-9db5-c3462e4d7d73.lb.civo.com
